general:
  update_interval: 10

mqtt:
  host: localhost
  port: 1883
  default_prefix: brno

sensors:
#  - platform: ds18b20
#    name: ds18b20
#    temperature_topic: ds18b20/temperature
#    update_interval: 10

  - platform: HTU21
    name: HTU21
    temperature_topic: HTU21/temperature
    humidity_topic: HTU21/humidity
    bus_number: 1
    update_interval: 10

  - platform: Bmp180
    name: Bmp180
    temperature_topic: Bmp180/temperature
    abs_pressure_topic: Bmp180/abs_pressure
    rel_pressure_topic: Bmp180/rel_pressure
    altitude: 253
    update_interval: 10
